// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFZquZ2SwxD3u2seVX31SBXU8oBkKY0J0',
    appId: '1:770664252607:web:f9d255d4621a2b1eb0320a',
    messagingSenderId: '770664252607',
    projectId: 'nssams-fc85d',
    authDomain: 'nssams-fc85d.firebaseapp.com',
    storageBucket: 'nssams-fc85d.firebasestorage.app',
    measurementId: 'G-8SJ2T2N55L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCda1IWQ6gCR9ixOIRdCCCjJv2-Hhoujt8',
    appId: '1:770664252607:android:8db3643ffc2f4af3b0320a',
    messagingSenderId: '770664252607',
    projectId: 'nssams-fc85d',
    storageBucket: 'nssams-fc85d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZbF5GGuZ7EIujEfDGEIZstvDGITKbRUI',
    appId: '1:770664252607:ios:6cbbb589fba8eb50b0320a',
    messagingSenderId: '770664252607',
    projectId: 'nssams-fc85d',
    storageBucket: 'nssams-fc85d.firebasestorage.app',
    iosBundleId: 'com.example.nssams',
  );
}
